[package]
name = "oxi-luvit"
description = "Rust bindings to luvit for nvim-oxi"
version.workspace = true
edition.workspace = true
repository.workspace = true
documentation.workspace = true
license.workspace = true

[dependencies]
oxi-luajit = { workspace = true }

once_cell = "1.17"
